name: payment-web-platform-local

services:
  postgres:
    image: postgres:18.4-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    container_name: payment-web-platform-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payment_platform
      POSTGRES_USER: payment_dev
      POSTGRES_PASSWORD: payment_dev
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - payment_postgres18_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_dev -d payment_platform"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  redis:
    image: valkey/valkey:7.2.13-alpine@sha256:ac32d5e70f29e2be83384f5173180911b666c79a0e91ac0d074de5771638ed91
    container_name: payment-web-platform-redis
    restart: unless-stopped
    command: ["valkey-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:16379:6379"
    volumes:
      - payment_redis_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

volumes:
  payment_postgres18_data:
    name: payment-web-platform-postgres18-data
  payment_redis_data:
    name: payment-web-platform-redis-data
