export const PERMISSION_CODES = {
  userView: 'user:view',
  userCreate: 'user:create',
  userUpdate: 'user:update',
  userDelete: 'user:delete',
  userDisable: 'user:disable',
  userAssignRole: 'user:assign-role',
  roleView: 'role:view',
  roleCreate: 'role:create',
  roleUpdate: 'role:update',
  roleDelete: 'role:delete',
  roleGrantUpdate: 'role:grant-update',
  menuView: 'menu:view',
  menuCreate: 'menu:create',
  menuUpdate: 'menu:update',
  menuDelete: 'menu:delete',
  departmentView: 'department:view',
  departmentCreate: 'department:create',
  departmentUpdate: 'department:update',
  departmentDelete: 'department:delete',
  dictionaryView: 'dictionary:view',
  dictionaryCreate: 'dictionary:create',
  dictionaryUpdate: 'dictionary:update',
  dictionaryDelete: 'dictionary:delete',
  dictionaryDataView: 'dictionary-data:view',
  dictionaryDataCreate: 'dictionary-data:create',
  dictionaryDataUpdate: 'dictionary-data:update',
  dictionaryDataDelete: 'dictionary-data:delete',
  merchantSelfView: 'merchant:self-view',
  merchantSubmit: 'merchant:submit',
  merchantResubmit: 'merchant:resubmit',
  merchantView: 'merchant:view',
  merchantUpdate: 'merchant:update',
  merchantCreate: 'merchant:create',
  merchantAmend: 'merchant:amend',
  merchantDocumentUpload: 'merchant:document:upload',
  merchantDocumentView: 'merchant:document:view',
  merchantReview: 'merchant:review',
  merchantDisable: 'merchant:disable',
  merchantEnable: 'merchant:enable',
  merchantTerminate: 'merchant:terminate',
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];
